packages:
  - apps/astro-emdash
allowBuilds:
  workerd: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260930.1'
  - miniflare@5.20260926.1-alpha
  - wrangler@4.144.0
