/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/realtime/wrangler.jsonc --include-runtime=false --env-interface=RealtimeEnv workers/realtime/worker-configuration.d.ts` (hash: a1c57cd9c10ff46e48a93ed0340e8be6)
interface __BaseEnv_RealtimeEnv {
	ALLOWED_ORIGINS: "https://www.hugohsi.dev,https://hugohsi.dev";
	BOARD_RESET_TOKEN: string;
	PORTFOLIO_ROOMS: DurableObjectNamespace<import("./index").PortfolioRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "PortfolioRoom";
	}
	interface Env extends __BaseEnv_RealtimeEnv {}
}
interface RealtimeEnv extends __BaseEnv_RealtimeEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "BOARD_RESET_TOKEN">> {}
}
